CREATE TABLE `smartparking`.`sensor_config` (
`wpsConfigID` 		INT UNSIGNED NOT NULL AUTO_INCREMENT,
`ConfigTime`     	DATETIME NULL,
`coordSerial`      	TINYTEXT NOT NULL,
`serialBLE`      	TINYTEXT NOT NULL,
`wpsAddress`        TINYINT UNSIGNED NOT NULL,
`wpsNetworkID`		TINYINT UNSIGNED NOT NULL,
`wpsSerialMSB`     	TINYTEXT NULL,
`wpsSWVersion`      TINYTEXT NOT NULL,
`wpsHWVersion`      TINYINT UNSIGNED NOT NULL,
`wpsmagZ`           TINYINT UNSIGNED NOT NULL,
`wpsmagXY`          TINYINT UNSIGNED NOT NULL,
`wpsreadFRQ`        TINYINT UNSIGNED NOT NULL,
`wpsVarianceOrDiff` TINYINT UNSIGNED NOT NULL,
`wpsvectorVarBase`  TINYINT UNSIGNED NOT NULL,
`wpsVectorVarLim`   TINYINT UNSIGNED NOT NULL,
`wpsCheckRSSI`      TINYINT UNSIGNED NOT NULL,
`wpsMinRSSIdif`     TINYINT UNSIGNED NOT NULL,
`wpsMaxRSSIdif`     TINYINT UNSIGNED NOT NULL,
`wpsRadioTXpower`   TINYINT UNSIGNED NOT NULL,
`wpsBLETXpower`     TINYINT UNSIGNED NOT NULL,
`wpsVehicDetCnt`    TINYINT UNSIGNED NOT NULL,
`wpsSleepCount`     TINYINT UNSIGNED NOT NULL,
`wpsLoraChannel`    TINYINT UNSIGNED NOT NULL,
`wpsLoraFRQ`        FLOAT(3.2) NULL,
`wpsdiffMultiplier` TINYINT UNSIGNED NOT NULL,
`wpsSensorGain`     TINYINT UNSIGNED NOT NULL,
`wpsBLEWaitTimeout` TINYINT UNSIGNED NOT NULL,
`wpsModemConfigNum` TINYINT UNSIGNED NOT NULL,
`wpsContMode`       TINYINT UNSIGNED NOT NULL,
PRIMARY KEY (`wpsConfigID`));


CREATE TABLE `smartparking`.`sensor_log` (
`wpsLogID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`serialBLE`      	TINYTEXT NOT NULL,
`wpsSequence`       INT UNSIGNED NOT NULL,
`VehicleStatus`  	TINYTEXT NULL,
`VectorVariance`    TINYINT UNSIGNED NOT NULL,
`mqttMsgTime`     	DATETIME NULL,
`loraMsgTime`     	DATETIME NULL,
`wpsBarStatus`      TINYTEXT NULL,
`wpsMagError`       TINYINT UNSIGNED NOT NULL,
`wpsBLEError`       TINYINT UNSIGNED NOT NULL,
`wpsLoraTXError`    TINYINT UNSIGNED NOT NULL,
`LastTXRetryCount`  TINYINT UNSIGNED NOT NULL,
`wpsTemperature` 	FLOAT(3.2) NULL,
`wpsBatteryVoltage` FLOAT(3,2) NULL,
`wpsBatteryLevel`   TINYINT UNSIGNED NULL,
`wpsSideRSSI`       TINYINT NULL,
`coordSideRSSI`     TINYINT NULL,
`packageType`      	TINYTEXT NOT NULL,
'vectorValue' 		FLOAT NULL,
PRIMARY KEY (`wpsLogID`));
